apiVersion: apps/v1
kind: Deployment
metadata:
  name: serrano-rot-engine
#  namespace: serrano
spec:
  selector:
    matchLabels:
      app: serrano-rot-engine
  replicas: 2
  template:
    metadata:
      labels:
        app: serrano-rot-engine
    spec:
      imagePullSecrets:
      - name: serrano-registry-key
      containers:
      - name: serrano-rot-engine
        image: ictserrano/serrano:rot-v1.0
        command: ["python3"]
        args: ["/home/serrano/serrano_rot/engineInstance.py"]
        imagePullPolicy: Always
        ports:
        - containerPort: 10020
        volumeMounts:
        - name: rot-engine-config
          mountPath: /etc/serrano
      volumes:
       - name: rot-engine-config
         configMap:
           name: rot-engine-config


