apiVersion: v1
kind: Service
metadata:
  name: serrano-rot-controller-service
  namespace: integration
spec:
  type: NodePort
  selector:
    app: serrano-rot-controller
  ports:
    - protocol: TCP
      port: 10020
      targetPort: 10020
      nodePort: 10020


