apiVersion: v1
kind: Service
metadata:
  name: serrano-rot-pipeline
  labels:
    app: serrano-rot-pipeline
spec:
  type: NodePort
  ports:
    - name: serrano-rot-pipeline
      port: 10020
      protocol: TCP
      nodePort: 10020
  selector:
    matchLabels:
      app: "serrano-rot-pipeline"