apiVersion: v1
kind: Service
metadata:
  name: serrano-rot-pipeline
  labels: serrano-rot-pipeline
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: serrano-rot-pipeline
  
