apiVersion: v1
kind: Service
metadata:
  name: {{ include "serrano-rot-controller.fullname" . }}
  labels: 
    {{- include "serrano-rot-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: 
    {{- include "serrano-rot-controller.selectorLabels" . | nindent 4 }}